### ISSUE TITLE
error reading env variables

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/cerise#67]
```
[2017-12-14 15:11:35.815] [CRITICAL] Traceback (most recent call last):
  File "cerise/run_back_end.py", line 48, in <module>
    manager = ExecutionManager(config, apidir, xenon_)
  File "cerise/../cerise/back_end/execution_manager.py", line 38, in __init__
    self._remote_files = XenonRemoteFiles(self._job_store, xenon, config)
  File "cerise/../cerise/back_end/xenon_remote_files.py", line 45, in __init__
    self._fs = config.get_file_system()
  File "cerise/../cerise/config.py", line 242, in get_file_system
    credential = self._get_credential('files', protocol, location)
  File "cerise/../cerise/config.py", line 132, in _get_credential
    username = self._get_credential_variable(kind, 'username')
  File "cerise/../cerise/config.py", line 60, in _get_credential_variable
    value = get_env('', name)
  File "cerise/../cerise/config.py", line 54, in get_env
    return os.environ(env_var(kind, name))
TypeError: '_Environ' object is not callable
```

the problem is this line `  return os.environ(env_var(kind, name))` that should be   `return os.environ[env_var(kind, name)]`

**Comment by fabioespinosa** [comment]
change 
print(os.environ(['HOME']))

to 

print(os.environ['HOME'])

Notice that you are "calling" the environ instead of accessing it
