### ISSUE TITLE
configuration issue 

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/cerise#68]
the new configuration triggers the following error:
```
[2017-12-14 16:26:32.425] [CRITICAL] Traceback (most recent call last):
  File "cerise/run_back_end.py", line 48, in <module>
    manager = ExecutionManager(config, apidir, xenon_)
  File "cerise/../cerise/back_end/execution_manager.py", line 64, in __init__
    api_files_path, api_install_script_path)
  File "cerise/../cerise/back_end/xenon_job_runner.py", line 30, in __init__
    self._sched = config.get_scheduler()
  File "cerise/../cerise/config.py", line 224, in get_scheduler
    scheme, location, credential, properties)
jpype._jexception.nl.esciencecenter.xenon.XenonExceptionPyRaisable: nl.esciencecenter.xenon.XenonException: slurm adaptor: could not run command "
scontrol" with stdin "null" arguments "[show, config]" at "SchedulerImplementation [uniqueID=ssh1, adaptorName=ssh, scheme=ssh, location=fs0.das5.
cs.vu.nl, properties={<<xenon.adaptors.ssh.strictHostKeyChecking=true>>, xenon.adaptors.ssh.queue.pollingDelay=100, <<xenon.adaptors.ssh.queue.mul
ti.maxConcurrentJobs=4>>, <<xenon.adaptors.ssh.autoAddHostKey=true>>, <<xenon.adaptors.ssh.gateway=null>>}, queueNames=[single, multi, unlimited],
 isOnline=true, supportsInteractive=true, supportsBatch=true]". Exit code = 0 Output: Configuration data as of 2017-12-14T17:26:32

```

**Comment by LourensVeen** [comment]
I can't reproduce this with cerise-mdstudio-das5.

The Dockerfile in that repo has a `FROM cerise` statement. Could you change that to `FROM mdstudio/cerise:develop`, docker pull that image, and then rebuild the specialisation? It may be that you have a stale Cerise image that's the problem.

**Comment by felipeZ** [comment]
Sorry, my mistake.
I have a variable in the `bashrc` pointing to a file that is not there because it is installed by Cerise.
